#!/bin/tcsh -f

#set project = cpc_fifo
set project = cpc_fifo_sn74

# Need to have access to the Jython netlister program
set netlister_dir = ~/Documents/nas/Development/git/netlister
which netlister.py > /dev/null
if ($status != 0) then
   setenv CLASSPATH ${netlister_dir}/src:$CLASSPATH
   setenv PATH      ${netlister_dir}/src:$PATH
   rehash
endif

setenv TERM xterm


cp ../common_pcb/autorouter.ctl /tmp

make ${project}.scr  -f ../common_pcb/Makefile
make ${project}.net -f ../common_pcb/Makefile


